fixed issues #426 - saving a display picture locally
zurichat/zc_app pull request #591
Opened 2021-09-04 09:21 UTC by toogood208

## This solves issue #406, saving a display picture locally

please note that as of the time of this writing, the profile page that houses the display picture has not been built, so I had to create a temporary page to test this fix.
the developer assigned to the profile page can delete the temporary page when he is ready, he should also not forget to call the  savePictureLocally function from the profile_page_viewmodel class

![20210904_100637 1](https://user-images.githubusercontent.com/82845772/132089349-9f4bddb7-346e-47a0-8b0f-0a3737dfd400.gif)

[link to appetizer](https://appetize.io/app/y081qhtahv3me9jfc0w0j8f9gg?device=nexus5&scale=75&orientation=portrait&osVersion=8.1)

2021-09-04 21:07 UTC, Quwaysim approved these changes

2021-09-05 07:52 UTC, Quwaysim requested changes
Don't PR to master.

2021-09-05 07:53 UTC, Quwaysim commented
and fix your conflicts

2021-09-05 08:04 UTC, mayor04 commented
Create another pull request to the dev branch not master

2021-09-05 19:31 UTC, merged