Feat: Improved and Implemented UI for DM View between two users.
zurichat/zc_app pull request #740
Opened 2021-09-18 07:37 UTC by YenumJay

This implements the Improved UI design for DM View between two Users and the codes were refactored to enable scalable implementation for the next steps of this workflow(Send Messages In DMs).

Currently, the Messages in DM are run on Simulation.

This addresses this issue #739 

![DM VIEW](https://user-images.githubusercontent.com/80979473/133880422-ce1023f2-9c8c-486a-b024-04837c16a357.gif)

2021-09-18 08:58 UTC, isaacadariku requested changes
Good, make the few changes requested and we are good to go.

2021-09-18 08:58 UTC, isaacadariku commented on lib/ui/nav_pages/dm_page/dm_page_viewmodel.dart
> +    locator<NavigationService>().navigateTo(Routes.dmUserView);
Can kindly make the `NavigationService()` a variable to be use.

`final _navigationService = locator<NavigationService>();`

2021-09-18 08:58 UTC, isaacadariku commented on lib/ui/nav_pages/dm_page/widgets/dmmessage_read.dart
> +        locator<NavigationService>().navigateTo(Routes.dmUserView);
Move this logic away from the view, and put in the viewmodel, also follow the above request

2021-09-18 08:58 UTC, isaacadariku commented on lib/ui/nav_pages/dm_page/widgets/dmmessage_unread.dart
> +        locator<NavigationService>().navigateTo(Routes.dmUserView);
Here too

2021-09-18 08:58 UTC, isaacadariku commented on lib/ui/shared/styles.dart
> +  static Widget statusIcon(int count) {
Can you remove the static keyword here and make the widget in a class, functional widgets are bad practice in flutter.

2021-09-18 08:58 UTC, isaacadariku commented on lib/ui/view/dm_user/dm_user_viewmodel.dart
> +import 'package:hng/ui/view/dm_user/widgets/custom_status.dart';
No import of UI in the viewmodel

2021-09-18 14:43 UTC, isaacadariku requested changes
Few changes and we good

2021-09-18 14:43 UTC, isaacadariku commented on lib/ui/view/dm_user/widgets/group_separator.dart
> +Widget groupSeparator(String value) {
I spoke about functional widgets are not allowed, ensure it have it's class

2021-09-19 08:06 UTC, mariamadebolahamzat approved these changes
All reviews has been resolved..

2021-09-19 09:45 UTC, isaacadariku approved these changes
LGTM

2021-09-19 09:46 UTC, merged