Threads Page implementation
zurichat/zc_app pull request #770
Opened 2021-09-20 16:03 UTC by pauleke65

2021-09-20 16:20 UTC, Quwaysim requested changes
please make changes...

GREAT work!!

2021-09-20 16:20 UTC, Quwaysim commented on lib/models/user_post.dart
> +enum ChannelType { private, public, personal }
move enum to lib/utilities/enums.dart

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/shared/bottom_sheets/custom_user_bottomsheet/custom_user_bottom_sheet_view.dart
> +                              child: Icon(Icons.looks_5, color: Colors.blue)),
extract colors to the AppColors class

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/shared/bottom_sheets/custom_user_bottomsheet/widgets/custom_button.dart
> +enum _CustomButtonType { normal, icon }
move to enums.dart file

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/shared/bottom_sheets/custom_user_bottomsheet/widgets/custom_button.dart
> +              style: TextStyle(color: AppColors.greyishColor),
Use one of the const TextStyles or extract yours to the file

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/view/threads/threads_view.dart
> +                    text: 'No new replies',
use one of the const styles or create yours in styles.dart

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/view/threads/widgets/thread_card.dart
> +              text: 'You, Jane and 2 others',
styles.dart

2021-09-20 16:20 UTC, Quwaysim commented on lib/ui/view/threads/widgets/thread_post.dart
> +                            fontSize: 12,
styles here too

2021-09-20 17:23 UTC, pauleke65 reviewed
Changes made

2021-09-20 17:25 UTC, pauleke65 reviewed
changes made

2021-09-20 17:27 UTC, Quwaysim approved these changes
LG

2021-09-21 08:58 UTC, mariamadebolahamzat commented
Resolve conflicts

2021-09-22 06:50 UTC, mariamadebolahamzat approved these changes
All changes made

2021-09-22 07:17 UTC, Quwaysim approved these changes

2021-09-22 07:18 UTC, merged