signout workflow
zurichat/zc_app pull request #795
Opened 2021-09-22 15:57 UTC by edwinchiboy

We worked on the signout workflow

2021-09-24 22:37 UTC, Blazebrain commented
Fix Conflicts

2021-09-28 08:44 UTC, YenumJay commented
Pull latest changes from dev and resolve conflicts.

2021-09-28 15:39 UTC, pauleke65 requested changes
Changes Requested

2021-09-28 15:39 UTC, pauleke65 commented on lib/ui/view/sign_out/sign_out_view.dart
> +import 'package:flutter/foundation.dart';
Why is foundation being imported?

2021-09-28 15:39 UTC, pauleke65 commented on lib/ui/view/sign_out/sign_out_view.dart
> +class BottomsheetContent extends StatelessWidget {
Refactor to use bottom sheet service

2021-09-28 15:39 UTC, pauleke65 commented on lib/ui/view/sign_out/sign_out_view.dart
> +  Future<void> _showSignOutDialog(context) async {
Refactor to use Dialog Service

2021-09-28 15:39 UTC, pauleke65 commented on lib/ui/view/workspace/workspace_view/workspace_view.dart
> +import 'package:flutter/foundation.dart';
Foundation again?

2021-09-28 15:39 UTC, pauleke65 commented on lib/ui/view/workspace/workspace_view/workspace_view.dart
> +                                        showModalBottomSheet(
Add the bottom sheet service and the dialog from the model, which should use their respective services

2021-10-02 14:32 UTC, pauleke65 commented
Similar PR available [#828 ](https://github.com/zurichat/zc_app/pull/828)

2021-10-02 14:32 UTC, closed without merging