Delete channels workflow
zurichat/zc_app pull request #800
Opened 2021-09-23 10:57 UTC by HassanTeslim007

Workflow For Deleting channels completed

2021-09-24 22:42 UTC, Blazebrain commented
Fix Conflicts 

Also, does it return to the homepage after?

Once a channel is deleted, we should be directed to the homepage

2021-09-25 08:58 UTC, HassanTeslim007 commented
Conflicts Resolved and Yes, It returns to Homepage

2021-09-25 11:10 UTC, Blazebrain commented
Can you refix boss?

Still has some

2021-09-25 13:20 UTC, HassanTeslim007 commented
Fixed boss... again

2021-09-27 13:49 UTC, HassanTeslim007 commented
Finally, Fixed again.

2021-09-28 08:44 UTC, YenumJay commented
Pull latest changes from dev and resolve conflicts then you should be good.

2021-09-28 10:11 UTC, HassanTeslim007 commented
Done...

2021-09-28 15:14 UTC, jeremiahseun commented on lib/ui/nav_pages/home_page/home_page_viewmodel.dart
> +<<<<<<< HEAD
This line should not be there

2021-09-28 15:15 UTC, jeremiahseun commented on lib/ui/nav_pages/home_page/home_page_viewmodel.dart
> +>>>>>>> d4f077f1ecab6b315ee58c05d2e2116f60d012a3
This also
And line 147

2021-09-28 15:16 UTC, jeremiahseun commented on lib/ui/shared/dialogs/delete_channels_dialog.dart
> +          // titlePadding: EdgeInsets.fromLTRB(24.0, 24.0, 24.0, 0),
Please remove commented code when it's not been used

2021-09-28 15:16 UTC, jeremiahseun requested changes
Kindly make changes where required

2021-09-30 10:11 UTC, closed without merging