Preference in an Organization list
zurichat/zc_app pull request #825
Opened 2021-09-25 18:39 UTC by abdussamadbsg

Preference linked to the Organization list

2021-09-26 12:54 UTC, Blazebrain requested changes
Good to go

Asides that little tweak

Fix the change and we good to go

2021-09-26 12:54 UTC, Blazebrain commented on lib/ui/view/organization/organization_view/organization_view.dart
> +                                      final org = model.organizations[i];
Remove the priint statements in this screen

Replace them with the log.i()

2021-09-28 08:40 UTC, YenumJay commented
Pull latest changes from dev and resolve conflicts.

2021-09-28 15:10 UTC, jeremiahseun submitted a review, later dismissed
LGTM

2021-09-28 15:18 UTC, pauleke65 commented on lib/ui/view/organization/organization_view/organization_view.dart
> +                                      model.log.i(org.name);
Move all Log and logic statements to the view model

2021-09-28 15:20 UTC, pauleke65 commented on lib/ui/view/organization/organization_view/organization_viewmodel.dart
> +  Future viewPreferences() async {
change Future to Future<void>

2021-09-28 15:27 UTC, pauleke65 requested changes
Changes Requested

2021-09-29 05:15 UTC, pauleke65 submitted a review, later dismissed
Terrific👍🏽

2021-09-29 10:11 UTC, jeremiahseun commented
Please fix conflicts

2021-09-30 18:13 UTC, pauleke65 approved these changes
LG

2021-09-30 18:24 UTC, YenumJay approved these changes
Good to go

2021-09-30 18:25 UTC, merged