RegEx Update for Text parser
zurichat/zc_app pull request #848
Opened 2021-09-29 01:40 UTC by Starhkz

Includes unit test

2021-09-29 04:51 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
> +import 'package:url_launcher/url_launcher.dart';
This shouldn't be here.
Use the one in lib/utilities/utilities.dart
You can fix it up there if it's not working

2021-09-29 13:33 UTC, jeremiahseun approved these changes
Awesome.
LGTM

2021-09-29 17:57 UTC, pauleke65 requested changes
I didn't mean remove the url launcher completely, i meant import it from the utilities folder instead of importing it here

2021-10-01 14:44 UTC, YenumJay requested changes
Good job so far, few changes and you are good.

1. Use standard practices to describe your test cases.

2. Mock your unit test (Use the current Mockito Test Setup already done and register your service and mock your values)

3. Record your device while running your unit test to show the green checks and output results.

2021-10-02 13:53 UTC, jeremiahseun submitted a review, later dismissed
LGTM

2021-10-02 15:01 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
> +        pattern: r'\B#+([\w]+)\b',
no parsed type here, use custom

2021-10-02 15:01 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
> +        pattern: r'\B@+([\w]+)\b',
and here

2021-10-02 15:01 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
> +        pattern: 'keyword',
here too

2021-10-02 15:03 UTC, pauleke65 commented on test/services/text_parser_test.dart
> +    test("Returns true if it contains hashtag", () async {
hashtag or keyword?

2021-10-02 15:17 UTC, Starhkz commented on test/services/text_parser_test.dart
> +    test("Returns true if it contains hashtag", () async {
Edited

2021-10-02 15:18 UTC, Starhkz commented on lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
> +        pattern: r'\B@+([\w]+)\b',
Done

2021-10-02 15:26 UTC, pauleke65 requested changes
Please make requested changes and 
write an additional test for this for the channels text parser -> "this is a channel called @#channel-name-here and fine"

This should return #channel-name-here , not #channel, or @#channel

2021-10-02 18:16 UTC, pauleke65 approved these changes
LGTM

2021-10-02 18:26 UTC, YenumJay approved these changes
Great, Looks good.

2021-10-02 18:26 UTC, merged