Added scheduling messages feature
zurichat/zc_app pull request #907
Opened 2021-10-06 15:33 UTC by Starhkz

The video below shows how it's used

https://user-images.githubusercontent.com/67955282/136237888-927bfe71-75d7-4e14-8776-45f2b3d89754.mp4

The message will appear in 30 minutes.

2021-10-06 15:50 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +            appBar: AppBar(
Please use ZuriAppBar

2021-10-06 15:51 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +  TextEditingController messageController = TextEditingController();
This should not be here

2021-10-06 15:51 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
>    final _scrollController = ScrollController();
This too

2021-10-06 15:54 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                            color: Color(0xFF424141),
What happens to AppColors? Please use it

2021-10-06 15:54 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                            color: Color(0xFF424141),
Here too

2021-10-06 15:54 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                            color: Color(0xFF424141),
Here too

2021-10-06 15:55 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                        // duration: Duration(milliseconds: 500),
Remove unused commented code

2021-10-06 15:55 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                // Padding(
Remove code if you're not using please

2021-10-06 15:55 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +        Navigator.pop(context, time.toString());
This is wrong

2021-10-06 23:24 UTC, jeremiahseun requested changes
Please make changes.

Please try to wrap your schedule message function in a try catch block and then send a message, then wait for the time stipulated and see if the message truly sends or throws an error.

2021-10-06 23:24 UTC, jeremiahseun commented on lib/ui/shared/zuri_appbar.dart
> +      elevation: elevation,
No sir, this will not be possible. We are using **elevation: 2.0** throughout the app.

Kindly change it back

2021-10-06 23:24 UTC, jeremiahseun commented on lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
> +      _channelsApiService.sendChannelMessages(channelID, "$userId", text);
Did you try this and it worked? Where are you passing the token for sending messages?

2021-10-06 23:24 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_viewmodel.dart
> +        //clearText();
Please remove unsed codes

2021-10-07 02:09 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/expandable_textfield/expandable_textfield_screen.dart
> +                                                context: context,
Please use a dialog service for this

2021-10-07 02:10 UTC, pauleke65 commented on lib/ui/shared/smart_widgets/expandable_textfield/expandable_textfield_screen.dart
> +class ScheduleOption extends StatelessWidget {
Also, create a file for this in the widgets directory and place it there

2021-10-07 02:11 UTC, pauleke65 requested changes
Great Work, please make minor changes

2021-10-08 01:20 UTC, jeremiahseun requested changes
Please make changes requested

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +    //final String orgName = request.data!;
Since it's not in use, please remove

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +                DmUserViewModel model = DmUserViewModel();
Look at line 6 comment of this file

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +class ScheduleMess extends StatelessWidget {
`class ScheduleMess extends ViewModelWidget<DmUserViewModel>`

This line will avoid you calling the viewmodel in your onPressed.

Now check line 14

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +  Widget build(BuildContext context) {
`Widget build(BuildContext context, DmUserViewModel model) {}`

Now you can just use the `model.` anywhere in this file.

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +                DmUserViewModel model = DmUserViewModel();
Please remove

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +                DmUserViewModel model = DmUserViewModel();
Here too

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/shared/dialogs/schedule_dialog.dart
> +                DmUserViewModel model = DmUserViewModel();
Here too

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +  TextEditingController messageController = TextEditingController();
It should not be here

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                      onFocusChange: (focus) {
You can move this whole function to the viewmodel

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +                                        onChanged: (value) {
Do the same for the onChanged.
Move it to the viewmodel

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +  final BuildContext context;
You're calling this twice

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +  final TextEditingController messageController;
We don't declare Text editing controller like this in Stacked

2021-10-08 01:20 UTC, jeremiahseun commented on lib/ui/view/dm_user/dm_user_view.dart
> +  final DmUserViewModel model;
Do the way I explain in the fine above

2021-10-08 18:12 UTC, pauleke65 submitted a review, later dismissed
LG

2021-10-12 07:46 UTC, closed without merging