Implemented User mentions in textfield
zurichat/zc_app pull request #942
Opened 2021-10-12 17:00 UTC by alecxchuk

@pauleke65 @jeremiahseun @YenumJay

2021-10-12 17:52 UTC, YenumJay requested changes
Not sure what was done. Please rename your PR and add a description.

2021-10-14 10:48 UTC, jeremiahseun requested changes
Please make changes and we are good to go

2021-10-14 10:48 UTC, jeremiahseun commented on lib/ui/view/expandable_textfield/expandable_textfield_screen_viewmodel.dart
> +  // void showMembersList(bool show) {
Please remove commented code

2021-10-15 14:38 UTC, jeremiahseun approved these changes
LGTM

2021-10-15 16:30 UTC, YenumJay approved these changes

2021-10-15 16:31 UTC, merged