Update User Status
zurichat/zc_app pull request #943
Opened 2021-10-12 17:01 UTC by Quwaysim

Update a user's status and reflect changes in U
![20211013225559](https://user-images.githubusercontent.com/35339083/137220514-ea9ed288-a271-4943-ad9f-22a7a0156796.gif)
I

2021-10-13 08:55 UTC, pauleke65 requested changes
Please add a description and title explaining your task🙏🏾

2021-10-15 20:08 UTC, pauleke65 submitted a review, later dismissed
LG

2021-10-16 00:19 UTC, pauleke65 approved these changes

2021-10-16 00:20 UTC, jeremiahseun approved these changes
LGTM

2021-10-16 00:21 UTC, merged